name: Check available lxc images
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - Available lxc alias
          - Available lxc images
          - Available lxc ubuntu images
        include:
          - label: Available lxc alias
            script: ./alias.sh
          - label: Available lxc images
            script: ./images.sh
          - label: Available lxc ubuntu images
            script: ./ubuntu.sh
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ${{ matrix.script }}
  launch:
    name: Launch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - Ubuntu 24.04
          - CentOS 7
          - AmazonLinux 2
          - AmazonLinux 2023
        include:
          - label: Ubuntu 24.04
            image: ubunutu:n
          - label: CentOS 7
            image: images:centos/7
          - label: AmazonLinux 2
            image: images:amazonlinux/2
          - label: AmazonLinux 2023
            image: images:amazonlinux/2023
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ./launch.sh ${{ matrix.image }}
