name: Check available lxc images
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - Available lxc alias
          - Available lxc images
          - Available lxc ubuntu images
        include:
          - label: Available lxc alias
            script: ./alias.sh
          - label: Available lxc images
            script: ./images.sh
          - label: Available lxc ubuntu images
            script: ./ubuntu.sh
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ${{ matrix.script }}
  launchv1:
    name: Launch CGroupV1
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        label:
          - Ubuntu 24.04
          - CentOS 7
          - CentOS 7 (alias)
          - CentOS 7 (amd64)
          - AmazonLinux 2
          - AmazonLinux 2023
        include:
          - label: Ubuntu 24.04
            image: ubuntu:n
          - label: CentOS 7
            image: images:centos/7
          - label: CentOS 7 (alias)
            image: centos/7
          - label: CentOS 7 (amd64)
            image: centos/7/amd64
          - label: CentOS 7 (figerprint)
            image: images:f4c23689f2c89ca2c6d6088e7fb8c02b34fb3b39700d757e3844041562c3df25
          - label: AmazonLinux 2
            image: images:amazonlinux/2
          - label: AmazonLinux 2023
            image: images:amazonlinux/2023
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ./launch.sh ${{ matrix.image }}
  launchv2:
    name: Launch CGroupV2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - RockyLinux 8
          - AlmaLinux 9
        include:
          - label: RockyLinux 8
            image: images:rockylinux/8
          - label: AlmaLinux 9
            image: images:almalinux/9
    steps:
      - uses: actions/checkout@master
      - uses: canonical/setup-lxd@v0.1.1
      - name: ${{ matrix.label }}
        run: ./launch.sh ${{ matrix.image }}
